#Configuation for centralized sampling
data_path:
  - location_data: "gt_GPS.txt"
    ground_truth_temperature_data: "gt_temperature.txt"
    initial_location_data: "init_GPS.txt"
    initial_temperature_data: "init_temperature.txt"

# learning parameter
learning_parameters:
  - convergence_threshold: 0.1
    max_iteration: 10
    model_update_rate: 1

# Gaussian Process parameter:
gp_parameters:
  - ground_truth_num_gaussian: 3
    num_gaussian: 3
    gp_hyperparameter: [0.5, 0.5, 0.5]
    gp_scale : 1000000.0

# sampling parameter
sampling_parameters:
  - heuristic_mode : 0
    Jackal_id: "Jackal"
    Pelican_id: "Pelican"
    scale_factor: [1.0, 0.5]
    variable_coeff: 0.5

# visualization
visualization_parameters:
  - map_frame: "gt" 
    map_id: 0
    x_scale: 0.5
    y_scale: 1.0
    x_offset: 0.0
    y_offset: 0.0
    lower_bound: -5.0
    upper_bound: 30.0
  - map_frame: "mean"
    map_id: 1
    x_scale: 0.5
    y_scale: 1.0
    x_offset: 150.0
    y_offset: 0.0
    lower_bound: -5.0
    upper_bound: 30.0
  - map_frame: "variance"
    map_id: 2
    x_scale: 0.5
    y_scale: 1.0
    x_offset: 300.0
    y_offset: 0.0
    lower_bound: -5.0
    upper_bound: 30.0
  - map_frame: "raw"
    map_id: 3
    x_scale: 2.5
    y_scale: 5.0
    x_offset: 30.0
    y_offset: 0.0
    lower_bound: -5.0
    upper_bound: 30.0
