#Configuation for centralized sampling
#
ground_truth_location_path: "/home/yunfei/Projects/heterogeneous-sampling/src/sampling_core/data/random_GPS.txt"
ground_truth_temperature_path: "/home/yunfei/Projects/heterogeneous-sampling/src/sampling_core/data/random_temperature.txt"

initial_location_path: "/home/yunfei/Projects/heterogeneous-sampling/src/sampling_core/data/random_GPS.txt"
initial_temperature_path: "/home/yunfei/Projects/heterogeneous-sampling/src/sampling_core/data/random_temperature.txt"


latitude_range: [40.4436052, 40.4436346]
longitude_range: [-79.9429624, -79.9429142]


# ground truth model information
ground_truth_num_gaussian: 3

# learning criteria
convergence_threshold: 0.1
max_iteration: 10
model_update_rate: 1

# visualization
visualization_frame_id: "/map"
visualization_namespace: "visualization"
ground_truth_visualization_id: 0
ground_truth_visualization_offset: -10
prediction_mean_visualization_id: 1
prediction_mean_visualization_offset: 0
prediction_var_visualization_id: 2
prediction_var_visualization_offset: 10
visualization_scale_x: 1.0
visualization_scale_y: 0.5
visualization_scale_z: 0.1
map_resolution: 0.000001

temperature_update_channel: "temperature_update_channel"

# gp parameter
num_gaussian: 3
gp_hyperparameter: [ 0.0000005, 0.0000005, -2.0]

interest_point_request_service_channel: "interest_point"
# 0 Variance 
# \todo yang add more modes
heuristic_mode : 0

Jackal_request_GPS_channel: "Jackal_GPS"
Pelican_request_GPS_channel: "Pelican_GPS"
Jackal_id: "Jackal"
Pelican_id: "Pelican"
scale_factor: [1.0, 0,5]
variable_coeff: 0.5
