#Configuation for centralized sampling
#
# ground_truth_location_path: "/home/yang/heterogeneous-sampling/bags/scripts/GPS.txt"
# ground_truth_temperature_path: "/home/yang/heterogeneous-sampling/bags/scripts/temperature.txt"

ground_truth_location_path: "/home/yang/heterogeneous-sampling/src/sampling_core/data/Xss.txt"
ground_truth_temperature_path: "/home/yang/heterogeneous-sampling/src/sampling_core/data/Fss.txt"

ugv_max_speed: 10
ugv_goal_channel: "test"
uav_max_speed: 10
uav_goal_channel: "test"

# ground truth model information
ground_truth_num_gaussian: 3

# learning criteria
convergence_threshold: 0.01
max_iteration: 100
model_update_rate: 10

# visualization
visualization_frame_id: "/map"
visualization_namespace: "visualization"
ground_truth_visualization_id: 10
ground_truth_visualization_offset: 50
prediction_mean_visualization_id: 1
prediction_mean_visualization_offset: 0
prediction_var_visualization_id: 2
prediction_var_visualization_offset: -50
visualization_scale_x: 1.0
visualization_scale_y: 1.0
visualization_scale_z: 0.1
map_resolution: 1.0

temperature_update_channel: "/temp"

# gp
gp_num_gaussian: 3
gp_hyperparam: [ 0.5, 0.5, -2.0]

