#Configuation for centralized sampling
#
ground_truth_location_path: "/home/yang/heterogeneous-sampling/src/sampling_core/data/Xss_gps.txt"
ground_truth_temperature_path: "/home/yang/heterogeneous-sampling/src/sampling_core/data/Fss_gps.txt"

ugv_max_speed: 10
ugv_goal_channel: "test"
uav_max_speed: 10
uav_goal_channel: "test"

# ground truth model information
ground_truth_num_gaussian: 3

# learning criteria
convergence_threshold: 0.01
max_iteration: 100

