num_gp: 3
gating: [1.0, 2.0, 3.0]
modeling_gp_0_kernel: [5.0, 1.0, 0.1]
gating_gp_0_kernel: [1.0, 0.5, 0.0]
modeling_gp_1_kernel: [3.0, 2.0, 0.1]
gating_gp_1_kernel: [2.0, 0.5, 0.0]
modeling_gp_2_kernel: [1.0, 3.0, 0.1]
gating_gp_2_kernel: [3.0, 0.5, 0.0]
noise_stdev: 0.1
EM_epsilon: 0.05
EM_max_iteration: 100