# ROSbridge websocket server info
rosbridge_ip: localhost
rosbridge_port: 9090
# Topics being published in the robot to expose locally
remote_topics: []
# Topics being published in the local roscore to expose remotely
local_topics: [
                ['/sampling_visualization/gt', 'visualization_msgs/Marker'],
                ['/sampling_visualization/mean', 'visualization_msgs/Marker'],
                ['/sampling_visualization/variance', 'visualization_msgs/Marker'],
                ['/sampling_visualization/raw', 'visualization_msgs/Marker']
              ]
# Services running in the robot to expose locally
remote_services: []
# Services running locally to expose to the robot
local_services: []
# Parameters to be sync, they will be polled to stay in sync
parameters: ['/robot_description', '/test_suite/param_1']
parameter_polling_hz: 1