#Configuation for jackal agent
ros_queue_size: 1
agent_id: 0
request_target_channel: "interest_point"
temperature_measurement_channel: "jackal_temperature_measurement"
temperature_update_channel: "temperature_update_channel"
gps_location_channel: "fix"
jackal_movebase_channel: "move_base"
jackal_movebase_goal_frame_id: "map"
jackal_moving_duration_threshold_s: 30
report_gps_location_channel: "Jackal_GPS"
facing_heatsource: true
heat_source_lat: 40.443345955
heat_source_lng: -79.94104499

poly_coeff: [3.934400, 1.998334, 0.577054, 0.108236, -0.983421, 
            -0.053012, -0.120888, 0.066311, 0.071316, 0.015456, 
            0.011875, 0.011496, -0.009661, 0.002992, -0.002209, 
            -0.000283, -0.000767, -0.000017, 0.000151, -0.000222, 0.000080]
observation_noise_std: 0.65
get_ground_truth: True
lat_constant: 40.443
lng_constant: -79.940


