#Configuation for artifical data
latitude_range: [40.443300, 40.443362]
longitude_range: [-79.941108, -79.941013]
scale: 1000000.0
heatsource_latitude: []
heatsource_longitude: []
heatsource_temperature: []
heatsource_range: []
# heatsource_latitude: [40.443345955]
# heatsource_longitude: [-79.94104499]
# heatsource_temperature: [25.0]
# heatsource_range: [0.00001]
noise: 0.5
ambient_temp: 1.5