#Common Configuation for fake agents
ros_queue_size: 1
request_target_channel: "interest_point"
temperature_measurement_channel: "fake_agent_temperature_measurement"
temperature_update_channel: "fake_agent_temperature_update_channel"
report_gps_location_channel: "Fake_GPS"
fake_moving_duration_threshold_s: 10
# fake_distance_threshold_s: 0.1
nagivate_loop_rate: 5 #10
# for dwa planner
num_speed_premitive: 20
orientation_resolution: 0.01
# collision_radius: 2
# obstacle_pos: [5,4,
#                8,6,
#                2,13]
# collision_radius: 2
# obstacle_pos: [6,7,
#                5,10,
#                2,2]
collision_radius: 2
obstacle_pos: [2,3,
               8,6,
               2,13,
               3,11]
random_initial_pos: True

prediction_time: 1 #2
goal_cost_gain: 0.3
obstacle_cost_gain: 0.7
# To create groundtruth distribution
ground_truth_type: 1 #0: gaussian, 1: poly fitted groundtruth
# 0. mvn distribution
observation_noise_std: 0.15
ground_truth_mu: [5, 15, 
                  10, 33, 
                  41, 23]

ground_truth_sig: [5, 3, 
                   12, 8, 
                   4, 8]
gaussian_weights: [2000,1400,1500]
# 1. groundtruth_fitted with poly55:

# 3 routers
poly_coeff: [3.934400, 1.998334, 0.577054, 0.108236, -0.983421, 
            -0.053012, -0.120888, 0.066311, 0.071316, 0.015456, 
            0.011875, 0.011496, -0.009661, 0.002992, -0.002209, 
            -0.000283, -0.000767, -0.000017, 0.000151, -0.000222, 0.000080]

# for data generation
map_range: [0,0,9,14] #lat1, lng1, lat2, lng2
map_resolution: 0.5
init_resolution: 5

