#Common Configuation for fake agents
ros_queue_size: 1
request_target_channel: "interest_point"
temperature_measurement_channel: "fake_agent_temperature_measurement"
temperature_update_channel: "fake_agent_temperature_update_channel"
report_gps_location_channel: "Fake_GPS"
fake_moving_duration_threshold_s: 40
fake_distance_threshold_s: 0.1
nagivate_loop_rate: 5 #10
# for dwa planner
speed_resolution: 0.01
orientation_resolution: 0.01
collision_radius: 1
# obstacle_pos: [4,3,
#                6,6,
#                8,7]
obstacle_pos: [1,2]
prediction_time: 1 #2
goal_cost_gain: 0.15
obstacle_cost_gain: 1


observation_noise_std: 0.1
# To create groundtruth distribution
ground_truth_mu: [8, 9, 
                  7, 10, 
                  1, 0]

ground_truth_sig: [0.1, 0.5, 
                   0.2, 0.8, 
                   0.001, 0.001]
gaussian_weights: [1,1,1]

