#Common Configuation for fake agents
ros_queue_size: 1
request_target_channel: "interest_point"
temperature_measurement_channel: "fake_agent_temperature_measurement"
temperature_update_channel: "fake_agent_temperature_update_channel"
report_gps_location_channel: "Fake_GPS"
fake_moving_duration_threshold_s: 20
# fake_distance_threshold_s: 0.1
nagivate_loop_rate: 5 #10
# for dwa planner
num_speed_premitive: 20
orientation_resolution: 0.01
collision_radius: 5
# obstacle_pos: [4,3,
#                6,6,
#                8,9]
obstacle_pos: [10,20]
prediction_time: 1 #2
goal_cost_gain: 0.15
obstacle_cost_gain: 1
# To create groundtruth distribution
observation_noise_std: 0.1
ground_truth_mu: [5, 15, 
                  10, 33, 
                  41, 23]

ground_truth_sig: [5, 3, 
                   12, 8, 
                   4, 8]
gaussian_weights: [2000,1400,1500]

