#Configuation for jackal agent

ros_queue_size: 10
agent_id: jackal
request_target_channel: "interest_point"
temperature_measurement_channel: "jackal_temperature_measurement"
temperature_update_channel: "tempp"
gps_location_channel: "fix"
jackal_movebase_channel: "move_base"
jackal_movebase_goal_frame_id: "map"
jackal_moving_duration_threshold_s: 30
