#Configuation for jackal agent
ros_queue_size: 1
agent_id: "Jackal"
request_target_channel: "interest_point"
temperature_measurement_channel: "jackal_temperature_measurement"
temperature_update_channel: "Jackal/temperature_update_channel"
gps_location_channel: "fix"
jackal_movebase_channel: "move_base"
jackal_movebase_goal_frame_id: "map"
jackal_moving_duration_threshold_s: 30
report_gps_location_channel: "Jackal_GPS"

facing_heatsource: true
heat_source_lat: 40.000010
heat_source_lng: -79.0000100