#Configuation for pelican agent
ros_queue_size: 10
agent_id: pelican
request_target_channel: "interest_point"
temperature_measurement_channel: "pelican_temperature_measurement"
temperature_update_channel: "temperature_update_channel"
gps_location_channel: "/fcu/gps"
xb_command_channel: "/write"
height_waiting_threshold: 5 #s
navigate_waiting_threshold: 5 #s waiting time before detecting convergence
maximum_navigation_time: 20 #s max navigation time, regarded fail if not converged
hover_height: 5000 #m
measure_height: 1500 #m
gps_converge_threshold: 1500 #1.5m
gps_converge_buffer_size: 5
nagivate_loop_rate: 10

latitude_origin: 40.443696
longitude_origin: -79.943044
